function skillsMember() {
    var skills = [
        'HTML',
        'CSS',
        'JavaScript',
        'React',
        'Node.js',
        'Express.js',
        'MongoDB',
        'Python',
        'Django',
        'Flask',
        'Java',
        'Spring',
        'Android',
        'MySQL',
        'PostgreSQL',
        'Oracle',
        'C#',
        'ASP.NET',
        'SQL Server',
        'C',
        'C++',
        'PHP',
        'Laravel',
        'Ruby',
        'Ruby on Rails',
        'Vue.js',
        'Angular',
        'Swift',
        'Kotlin',
        'Objective-C',
        'Go',
        'Rust',
        'Perl',
        'Scala',
        'Haskell',
        'Clojure',
        'Lua',
        'Bash/Shell',
        'PowerShell',
        'TypeScript',
        'R',
        'Groovy',
        'Matlab',
        'Assembly',
        'Kubernetes',
        'Docker',
        'Jenkins',
        'AWS',
        'Azure',
        'GCP',
        'Firebase',
        'Heroku',
        'Netlify',
        'Vercel',
        'Git',
        'GitHub',
        'GitLab',
        'Bitbucket',
        'Jira',
        'Trello',
        'Slack',
        'Discord',
        'Zoom',
        'Google Meet',
        'Microsoft Teams',
        'Webex',
        'VS Code',
        'Sublime Text',
        'Atom',
        'Vim',
        'IntelliJ IDEA',
        'Eclipse',
        'Visual Studio',
        'PyCharm',
        'WebStorm',
        'Postman',
        'Insomnia',
        'Swagger',
        'GraphQL',
        'REST API',
        'Socket.IO',
        'WebSockets',
        'jQuery',
        'Bootstrap',
        'Tailwind CSS',
        'Sass',
        'Less',
        'Materialize',
        'Ant Design',
        'Chakra UI',
        'Styled Components',
        'Redux',
        'MobX',
        'Flux',
        'Context API',
        'Next.js',
        'Gatsby',
        'Nuxt.js',
        'React Native',
        'Expo',
        'Ionic',
        'Flutter',
        'Xamarin',
        '